paratodo :: [Bool] -> Bool
paratodo ... = ...

sumatoria :: [Int] -> Int
sumatoria ... = ...

productoria :: [Int] -> Int
productoria ... = ...

factorial :: Int -> Int
factorial ... = ...

promedio :: [Int] -> Int
promedio ... = ...